spring:
  kafka:
    bootstrap-servers: localhost:9092

service1-topic: topic1
service2-topic: topic2
service1-group-id: group-id1
service2-group-id: group-id2
parallelism: 10


logging:
  level.root: error
  level:
#    org.apache.kafka: info
#    org.springframework.kafka: info
#    org.apache.kafka.clients.consumer.internals: info
    #    org.springframework.orm.jpa.JpaTransactionManager: trace
    #    org.springframework.kafka.transaction: trace
    #    org.springframework.kafka.core.DefaultKafkaProducerFactory: trace
    com.dragomir.fsm: debug
#    org.springframework.jdbc.core: TRACE